### ISSUE TITLE
most of the commands don't work

### ISSUE THREAD

**Issue by milan-hub** [Milo123459/salvage.db#2]
none of the commands work can you please update it I have used your videos as well

**Comment by Milo123459** [comment]
Hey, thanks for reaching out to me. Please can you let me know of what exactly doesn't work?

**Comment by milan-hub** [comment]
> Hey, thanks for reaching out to me. Please can you let me know of what exactly doesn't work?

The ban commands the help command and 2 other ones

**Comment by Milo123459** [comment]
What exactly has this got to do with **salvage.db** ?

**Comment by milan-hub** [comment]
> What exactly has this got to do with **salvage.db** ?

nothing

**Comment by Milo123459** [comment]
Then why are you making an issue here?

**Comment by milan-hub** [comment]
oh wait this is the wrong one sorry salvage_dev

**Comment by Milo123459** [comment]
No problem.
